export enum PaginationActionType {
  SET_USERS_PAGINATION = "pagination/SET_USERS_PAGINATION",
  SET_CHANNELS_PAGINATION = "pagination/SET_CHANNELS_PAGINATION",
  SET_CHANNEL_MEMBERS_PAGINATION = "pagination/SET_CHANNEL_MEMBERS_PAGINATION",
  SET_MEMBERSHIPS_PAGINATION = "pagination/SET_MEMBERSHIPS_PAGINATION",
  SET_HISTORY_PAGINATION = "pagination/SET_HISTORY_PAGINATION"
}
